language: en
pipeline:
  - name: SpacyNLP
    model: "en_core_web_md"
  - name: SpacyTokenizer # breaks down the sentences in tokens aka tokenization
  - name: SpacyFeaturizer # provides pre-trained word embeddings in English language
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: DIETClassifier
    epochs: 100
    entity_recognition: False
    constrain_similarities: true # this should help to better generalization to real world test sets
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 3
    epochs: 100
  - name: MappingPolicy